---
# Manifest file downloaded from fusion
externalId: tr-create_asset_hierarchy
name: create_asset_hierarchy
query: >-
    file: transformation.sql
destination:
    type: asset_hierarchy
ignoreNullFields: true
shared: true
action: upsert
schedule:
    interval: 35 * * * *
    isPaused: false
dataSetExternalId: src:001:sap:ds
# Specify credentials separately like this:
# authentication:
#   read:
#     authentication:
    clientId: 65f7112a-fddc-4663-a86c-d6a58d3fe9c7
    clientSecret: Xg~8Q~5_dgfFs0aQ~YM1YSMATp.GaQrwl5sfrcFK
    tokenUrl: https://login.microsoftonline.com/16e3985b-ebe8-4e24-9da4-933e21a9fc81/oauth2/v2.0/token
  # Optional: If idP requires providing the scopes
    cdfProjectName: bootcamp-72-test-all-owner-app
    scopes:
        - https://westeurope-1.cognitedata.com/.default
